#!/bin/bash
python pcd_ebm_ema.py \
    --dataset_name caltech \
    --sampler acs\
    --sampling_steps 30 \
    --viz_every 100 \
    --model resnet-64 \
    --print_every 10 \
    --lr .0001 \
    --warmup_iters 10000 \
    --burnin_adaptive \
    --buffer_size 1000 \
    --n_iters 50000 \
    --buffer_init mean \
    --base_dist \
    --reinit_freq 0.0 \
    --a_s_cut .7 \
    --eval_every 5000 \
    --eval_sampling_steps 10000 \
    --use_manual_EE \
    --steps_per_cycle 50 \
    --big_step_sampling_steps 5 \
    --big_step .5 \
    --small_step .2 \
    --save_dir raw_exp_data/ebm/acs/caltech_0.7_30 \
    --adapt_every 10 \
    --cuda_id $1
